name: Validation Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements_dev.txt

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests with tox
      run: |
        tox
